server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: false
    gateway:
      default-filters:
        - name: CircuitBreaker
          args:
            name: defaultCircuitBreaker
            fallback-uri: forward:/fallback/default
      routes:
        - id: auth-service
          uri: ${auth.service.url:http://localhost:8081}
          predicates:
            - Path=/api/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallback-uri: forward:/fallback/auth
        - id: coffee-service
          uri: ${coffee.service.url:http://localhost:8082}
          predicates:
            - Path=/api/coffee/**
          filters:
            - name: CircuitBreaker
              args:
                name: coffeeCircuitBreaker
                fallback-uri: forward:/fallback/coffee
        - id: email-service
          uri: ${email.service.url:http://localhost:8083}
          predicates:
            - Path=/api/email/**
          filters:
            - name: CircuitBreaker
              args:
                name: emailCircuitBreaker
                fallback-uri: forward:/fallback/email

  main:
    web-application-type: reactive

resilience4j:
  circuitbreaker:
    instances:
      authCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
      coffeeCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
      emailCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
      defaultCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    com.pagatu.gateway_service.filter: DEBUG

auth:
  service:
    url: ${AUTH_SERVICE_URL:http://localhost:8081}

coffee:
  service:
    url: ${COFFEE_SERVICE_URL:http://localhost:8082}

email:
  service:
    url: ${EMAIL_SERVICE_URL:http://localhost:8083}

jwt:
  secret: ${JWT_SECRET:pagatu_super_secure_secret_key_for_jwt_authentication_2025}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:8888,https://*.trycloudflare.com,https://*.ngrok-free.app}
  allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,PATCH,DELETE,OPTIONS,HEAD}
  allowed-headers: ${CORS_ALLOWED_HEADERS:Authorization,Content-Type,Accept-Language,Cache-Control,X-Requested-With,ngrok-skip-browser-warning,Accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers,Access-Control-Allow-Origin,X-Reset-Token}