spring:
  application:
    name: eureka-server

server:
  port: ${EUREKA_SERVER_PORT:8761}

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
  environment: ${EUREKA_ENVIRONMENT:dev}
  datacenter: ${EUREKA_DATACENTER:PagaTu-local}