name: GitLab Sync

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Sync to GitLab
        uses: keninkujovic/gitlab-sync@2.0.0
        with:
          gitlab_url: ${{ secrets.GIT_LAB_URI }}
          username: ${{ secrets.GIT_LAB_USERNAME }}
          gitlab_pat: ${{ secrets.GIT_LAB_TOKEN }}