name: GitLab Sync

on:
  workflow_dispatch:
    inputs:
      sync_reason:
        description: 'Reason for GitLab sync'
        required: false
        default: 'Manual sync'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Show sync reason
        run: |
          echo "🔄 GitLab Sync triggered: ${{ inputs.sync_reason || 'Manual sync' }}"
          
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Sync to GitLab
        uses: keninkujovic/gitlab-sync@2.0.0
        with:
          gitlab_url: ${{ secrets.GIT_LAB_URI }}
          username: ${{ secrets.GIT_LAB_USERNAME }}
          gitlab_pat: ${{ secrets.GIT_LAB_TOKEN }}